package modelos;
// Generated 12/11/2017 05:59:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private int clienteId;
     private Persona persona;
     private Set reservas = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(int clienteId) {
        this.clienteId = clienteId;
    }
    public Clientes(int clienteId, Persona persona, Set reservas) {
       this.clienteId = clienteId;
       this.persona = persona;
       this.reservas = reservas;
    }
   
    public int getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(int clienteId) {
        this.clienteId = clienteId;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


