package modelos;
// Generated 12/11/2017 05:59:15 PM by Hibernate Tools 4.3.1



/**
 * Consumo generated by hbm2java
 */
public class Consumo  implements java.io.Serializable {


     private int consumoId;
     private Producto producto;
     private Reserva reserva;
     private Integer cantidad;
     private String estado;

    public Consumo() {
    }

	
    public Consumo(int consumoId) {
        this.consumoId = consumoId;
    }
    public Consumo(int consumoId, Producto producto, Reserva reserva, Integer cantidad, String estado) {
       this.consumoId = consumoId;
       this.producto = producto;
       this.reserva = reserva;
       this.cantidad = cantidad;
       this.estado = estado;
    }
   
    public int getConsumoId() {
        return this.consumoId;
    }
    
    public void setConsumoId(int consumoId) {
        this.consumoId = consumoId;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


