package modelos;
// Generated 12/11/2017 05:59:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int productoId;
     private String nombre;
     private String descripcion;
     private String unidadMedida;
     private String precioVenta;
     private Set consumos = new HashSet(0);

    public Producto() {
    }

	
    public Producto(int productoId) {
        this.productoId = productoId;
    }
    public Producto(int productoId, String nombre, String descripcion, String unidadMedida, String precioVenta, Set consumos) {
       this.productoId = productoId;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.unidadMedida = unidadMedida;
       this.precioVenta = precioVenta;
       this.consumos = consumos;
    }
   
    public int getProductoId() {
        return this.productoId;
    }
    
    public void setProductoId(int productoId) {
        this.productoId = productoId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUnidadMedida() {
        return this.unidadMedida;
    }
    
    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    public String getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(String precioVenta) {
        this.precioVenta = precioVenta;
    }
    public Set getConsumos() {
        return this.consumos;
    }
    
    public void setConsumos(Set consumos) {
        this.consumos = consumos;
    }




}


