package Models;
// Generated 13/11/2017 12:29:04 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private int pagoId;
     private Reserva reserva;
     private String totalPago;
     private Date fechaEmision;
     private Date fechaPago;

    public Pago() {
    }

	
    public Pago(int pagoId) {
        this.pagoId = pagoId;
    }
    public Pago(int pagoId, Reserva reserva, String totalPago, Date fechaEmision, Date fechaPago) {
       this.pagoId = pagoId;
       this.reserva = reserva;
       this.totalPago = totalPago;
       this.fechaEmision = fechaEmision;
       this.fechaPago = fechaPago;
    }
   
    public int getPagoId() {
        return this.pagoId;
    }
    
    public void setPagoId(int pagoId) {
        this.pagoId = pagoId;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public String getTotalPago() {
        return this.totalPago;
    }
    
    public void setTotalPago(String totalPago) {
        this.totalPago = totalPago;
    }
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }




}


